#!/bin/sh

which -s nkf clang-format || (echo "Error: some command not available"; exit 1) || exit 1

SED=sed
which -s gsed && SED=gsed

(
	cd "$(dirname "$0")"
	git ls-files | grep -e '.*\.cpp$' -e '.*\.hpp$' | xargs $SED -i 's:#pragma://#pragma:g'
	git ls-files | grep -e '.*\.cpp$' -e '.*\.hpp$' | xargs clang-format -i
	git ls-files | grep -e '.*\.cpp$' -e '.*\.hpp$' | xargs $SED -i 's://#pragma:#pragma:g'
	git ls-files | grep -e '.*\.cpp$' -e '.*\.hpp$' | xargs nkf --in-place -Lw --oc=utf-8-bom
)
